// src/app/[locale]/impersonate-consume/page.tsx
//
// Landing page for the magic link generated by
// /api/admin/partners/[id]/impersonate/route.ts (redirectTo points
// here, same GoTrue mechanism as src/app/[locale]/set-password/page.tsx
// — see that file's comment for why detectSessionInUrl needs a plain
// client-mounted page rather than the actual portal page).
//
// MUST stay public (listed in PUBLIC_LOCALE_ROUTE_SEGMENTS in
// middleware.ts) for the same reason set-password is: the session
// tokens arrive in the URL hash fragment, which the server never sees,
// so a request to a gated route would 401/redirect before this page's
// client JS ever ran.
//
// The one thing this page does beyond set-password's pattern: it sets
// a sessionStorage flag so ImpersonationBanner (rendered in the partner
// portal layout) knows to show the "you are viewing as a partner"
// banner. sessionStorage (not a cookie) is deliberate — it's scoped to
// this one browser tab, so opening the impersonation link in a new tab
// (recommended — keeps the admin's own /admin session alive in the
// original tab) doesn't bleed the banner into tabs that aren't actually
// impersonating.
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

type SessionState = 'checking' | 'ready' | 'invalid';

// Parses GoTrue's own error out of the redirect (it appends
// #error=...&error_code=...&error_description=... to the hash instead of
// tokens when the link is genuinely rejected — expired, already used,
// or redirect_to not in the project's allowed Redirect URLs). Checking
// this up front means the 'invalid' state below reflects what actually
// happened instead of just "no session turned up after we waited."
function readAuthErrorFromUrl(): string | null {
  if (typeof window === 'undefined') return null;
  const fromParams = (params: URLSearchParams) => {
    const code = params.get('error_code');
    const desc = params.get('error_description');
    if (!code && !desc) return null;
    return [code, desc].filter(Boolean).join(': ');
  };
  return (
    fromParams(new URLSearchParams(window.location.hash.replace(/^#/, ''))) ??
    fromParams(new URLSearchParams(window.location.search))
  );
}

export default function ImpersonateConsumePage() {
  const router = useRouter();
  // Memoized so React 18 StrictMode's double-invoke of the component body
  // (dev mode only) doesn't create two GoTrueClient instances racing to
  // read/clear the #access_token hash in the URL — see file header comment.
  const [supabase] = useState(() => createClient('partner'));
  const [sessionState, setSessionState] = useState<SessionState>('checking');
  const [authError, setAuthError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    const urlError = readAuthErrorFromUrl();
    if (urlError) {
      // GoTrue already told us why — no point polling getSession() for
      // 3s just to show a generic message that may not match reality.
      setAuthError(urlError);
      setSessionState('invalid');
      return;
    }

    async function checkSession(attempt: number) {
      const { data } = await supabase.auth.getSession();
      if (cancelled) return;

      if (data.session) {
        sessionStorage.setItem('wos-impersonating', '1');
        setSessionState('ready');
        setTimeout(() => router.push('/th/dashboard'), 600);
        return;
      }

      if (attempt >= 10) {
        setSessionState('invalid');
        return;
      }

      setTimeout(() => checkSession(attempt + 1), 300);
    }

    // @supabase/ssr's createBrowserClient defaults to flowType: 'pkce',
    // under which detectSessionInUrl only recognizes a `?code=` query
    // param. admin.generateLink() (used by the impersonate route) always
    // issues the older implicit-flow style link instead — tokens in the
    // `#access_token=...&refresh_token=...` hash fragment — regardless
    // of this client's flowType, since GoTrue has no PKCE code_verifier
    // for a browser that never initiated the request. detectSessionInUrl
    // silently ignores that hash under pkce, so nothing was ever wrong
    // with the token itself: this client just never looked at it. Pull
    // the tokens out and set the session explicitly instead.
    const hashParams = new URLSearchParams(window.location.hash.replace(/^#/, ''));
    const accessToken = hashParams.get('access_token');
    const refreshToken = hashParams.get('refresh_token');

    async function establish() {
      if (accessToken && refreshToken) {
        const { error } = await supabase.auth.setSession({ access_token: accessToken, refresh_token: refreshToken });
        // Strip the tokens from the address bar either way — they're
        // single-use and shouldn't sit in browser history/referrers.
        window.history.replaceState(null, '', window.location.pathname);
        if (cancelled) return;
        if (error) {
          setAuthError(error.message);
          setSessionState('invalid');
          return;
        }
      }
      checkSession(0);
    }

    establish();

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((event, session) => {
      if (cancelled || !session) return;
      sessionStorage.setItem('wos-impersonating', '1');
      setSessionState('ready');
    });

    return () => {
      cancelled = true;
      subscription.unsubscribe();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="flex min-h-screen items-center justify-center bg-slate-50 px-4">
      <div className="w-full max-w-sm rounded-2xl border border-slate-100 bg-white p-8 text-center shadow-card">
        {sessionState === 'checking' && (
          <div className="text-sm text-slate-400">🔄 กำลังเข้าสู่ระบบแทนพาร์ทเนอร์...</div>
        )}
        {sessionState === 'ready' && (
          <div className="text-sm font-medium text-emerald-700">✅ เข้าสู่ระบบสำเร็จ กำลังพาไปหน้าแดชบอร์ด...</div>
        )}
        {sessionState === 'invalid' && (
          <div className="space-y-4">
            <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">
              ลิงก์หมดอายุหรือถูกใช้ไปแล้ว — กลับไปที่แอดมินแล้วลองใหม่อีกครั้ง
            </div>
            {authError && (
              <div className="text-left text-xs text-slate-400" title="ส่งข้อความนี้ให้ทีมพัฒนาถ้าปัญหาเกิดซ้ำ">
                {authError}
              </div>
            )}
            <a href="/admin" className="text-sm font-medium text-primary-dark hover:underline">
              กลับไปหน้าแอดมิน
            </a>
          </div>
        )}
      </div>
    </div>
  );
}
