// content/partner/en.ts
import type { PartnerPageContent } from "./types";

export const en: PartnerPageContent = {
  locale: "en",
  nav: {
    brand: "WOS Partner",
    mobileBrand: "WOS Partner",
    links: [
      { label: "Partner Benefits", href: "#why-partner" },
      { label: "How It Works", href: "#how-it-works" },
      { label: "Founding Partner", href: "#founding-partner" },
    ],
    cta: { label: "Apply Now", href: "/partner/apply" },
    mobileCtaLabel: "Apply",
  },
  hero: {
    eyebrow: "WOS PARTNER NETWORK",
    headlineLines: ["Connect your business", "with customers from Laos"],
    description:
      "WOS connects customers from Laos with healthcare and wellness providers in Thailand — covering planning, booking, travel and post-service care.",
    highlight: "Thailand × Laos",
    primaryCta: { label: "Become a Founding Partner", href: "/partner/apply" },
    secondaryCta: { label: "See partnership details", href: "#why-partner" },
    visual: { from: "Laos Customer", via: "WOS", to: "Thai Partner" },
  },
  whyPartner: {
    eyebrow: "WHY PARTNER WITH WOS",
    headline: "Reach new customers",
    subheadline: "With a service that goes beyond booking",
    cards: [
      {
        index: "01",
        title: "Reach New Customers",
        description: "Reach customers from Laos looking for healthcare and wellness services in Thailand.",
      },
      {
        index: "02",
        title: "One Complete Journey",
        description: "WOS coordinates booking, transport and hotel through to the appointment itself.",
      },
      {
        index: "03",
        title: "Performance-Based",
        description: "No setup fee and no monthly platform fee during the Founding Pilot.",
      },
    ],
  },
  journey: {
    eyebrow: "ONE COMPLETE JOURNEY",
    headline: "From Laos to Thailand",
    subheadline: "WOS supports the entire journey",
    steps: [
      { index: "01", title: "Discover", description: "Customers in Laos find the service that fits their needs." },
      { index: "02", title: "Plan", description: "WOS helps select the programme and plan the trip." },
      { index: "03", title: "Travel", description: "Transport, hotel and appointments are coordinated." },
      { index: "04", title: "Care", description: "The customer receives care from a WOS partner." },
      { index: "05", title: "Return", description: "WOS follows through until the customer is home again." },
    ],
    highlightTitle: "One Complete Journey",
    highlightText: "Not just a booking — the whole customer journey, start to finish.",
  },
  whoCanJoin: {
    eyebrow: "WHO CAN JOIN",
    headline: "WOS Partner Network",
    intro: "We are building a healthcare, wellness and hospitality network for customers from Laos.",
    groups: [
      { name: "Healthcare", items: ["Hospitals", "Clinics", "Dental", "Specialty centres"] },
      { name: "Wellness", items: ["Wellness Center", "Longevity", "Spa", "Recovery"] },
      { name: "Hospitality & Travel", items: ["Hotel", "Transport", "Travel Support"] },
    ],
    note: "Additional partner categories will be added as the network expands.",
  },
  foundingPartner: {
    eyebrow: "WOS FOUNDING PARTNER",
    headline: "Join the First Partner Network",
    intro:
      "Join the first cohort of WOS partners and help design services for the Lao market together with the WOS team.",
    privilegesHeadline: "Founding Partner Privileges",
    privileges: [
      { title: "No Setup Fee", description: "No setup cost to join." },
      { title: "No Monthly Platform Fee", description: "No monthly fee during the Pilot." },
      { title: "Priority Onboarding", description: "First access to onboarding." },
      { title: "Package Co-Design", description: "Design packages for the Lao market with us." },
      { title: "Partner Profile on WOS", description: "Present your business through WOS." },
      { title: "Cross-border Customer Opportunities", description: "Opportunities to receive customers from Laos." },
    ],
    badge: "LIMITED FIRST COHORT",
    cta: { label: "Become a Founding Partner", href: "/partner/apply" },
  },
  howItWorks: {
    eyebrow: "HOW IT WORKS",
    headline: "Getting started with WOS",
    steps: [
      { index: "01", title: "Apply", description: "Send us your partner information." },
      { index: "02", title: "Review", description: "The WOS team reviews your details and talks it through with you." },
      { index: "03", title: "Build", description: "We design packages and services for the Lao market together." },
      { index: "04", title: "Launch", description: "Start receiving customer journeys through WOS." },
    ],
    ctaHeadline: "Ready to grow with WOS?",
    cta: { label: "Become a Founding Partner", href: "/partner/apply" },
  },
  commercialModel: {
    eyebrow: "COMMERCIAL MODEL",
    headline: "Simple & Performance-Based",
    subheadline: "A cost structure that is easy to understand and only applies when a transaction happens.",
    cards: [
      { lead: "NO", term: "SETUP FEE", note: "No setup cost during the Founding Pilot." },
      { lead: "NO", term: "MONTHLY FEE", note: "No monthly platform fee during the Pilot." },
      {
        lead: "PAY",
        term: "WHEN BUSINESS HAPPENS",
        note: "A service fee applies per transaction — commercial terms and commission are agreed by partner type and service model.",
      },
    ],
    termsLink: { label: "View Partnership Terms", href: "/partner/terms" },
  },
  requirements: {
    eyebrow: "PARTNER REQUIREMENTS",
    headline: "What partners need to prepare",
    items: [
      "Business / Service Information",
      "Price & Package",
      "Availability / Booking Conditions",
      "Contact Person",
      "Supporting Documents",
    ],
    note: "The WOS team will guide and coordinate the onboarding steps with you.",
  },
  cta: {
    eyebrow: "JOIN THE NETWORK",
    headline: "Ready to grow with the Lao market?",
    subheadline: "Become a WOS Founding Partner",
    description:
      "WOS is opening its first partner cohort for cross-border healthcare and wellness between Laos and Thailand.",
    primaryCta: { label: "Become a Founding Partner", href: "/partner/apply" },
    secondaryCta: { label: "Talk to WOS Team", href: "/consultation" },
  },
  termsPage: {
    eyebrow: "PARTNERSHIP TERMS",
    headline: "Partnership details",
    intro:
      "Commercial details, MOU, responsibilities and service standards — for partners who want to review the full terms before deciding.",
    backLabel: "Back to Partner page",
    ctaHeadline: "Ready to start with WOS?",
    cta: { label: "Become a Founding Partner", href: "/partner/apply" },
  },
  commercialTerms: {
    headline: "Commercial Model",
    intro:
      "Performance-based Partnership — no setup fee and no monthly platform fee for Founding Partners during the pilot phase. WOS earns a service fee / commission on transactions, per the terms agreed in the Partner Agreement.",
    docStamp: "Founding Partner Terms",
    terms: [
      { label: "Setup fee", value: "None", note: "Founding Partners, during the Pilot" },
      { label: "Monthly platform fee", value: "None", note: "During the Pilot" },
      { label: "Commission / service fee", value: "Charged on actual transactions", note: "Per the terms agreed in the Partner Agreement" },
      { label: "Settlement cycle", value: "Monthly, within 30 days of billing cycle close" },
      { label: "Contract term", value: "1 year, auto-renews unless cancelled in advance" },
      { label: "Settlement currency", value: "THB / USD (by agreement)" },
    ],
    feeScheduleHeadline: "Fee schedule by partner type",
    feeSchedule: [
      { icon: "🏥", category: "Clinic / Medical Provider", fee: "15%", principle: "Charged on services originated through WOS" },
      { icon: "🌿", category: "Wellness / Spa", fee: "15%", principle: "Depends on the service and margin" },
      { icon: "🏨", category: "Hotel / Resort", fee: "12%", principle: "Suited to hotels with booking volume" },
      { icon: "🚐", category: "Transport", fee: "15%", principle: "Sedan / SUV / Van / VIP vehicles" },
      { icon: "🧘", category: "Fitness / Yoga / Activity", fee: "15%", principle: "Packages / activities" },
      { icon: "🥗", category: "Healthy Food", fee: "10%", principle: "Relatively low margin" },
      { icon: "🥊", category: "Muay Thai / Training", fee: "15%", principle: "Short- and long-term packages" },
      { icon: "👨‍⚕️", category: "Specialist / Consultant", fee: "10%", principle: "Professional service fees" },
      { icon: "📦", category: "WOS Bundled Journey", fee: "20%+", principle: "WOS bundles multiple services and manages the journey" },
    ],
    feeScheduleNote:
      "Fees may be adjusted based on booking volume, contract length, and partnership model — contact the WOS team for an offer tailored to your business.",
    disclaimer: "Full commission and contract terms are set out in the signed Pilot Agreement / MOU.",
  },
  mou: {
    headline: "MOU & Partnership Agreement",
    intro:
      "Every WOS partner signs a Memorandum of Understanding (MOU) before going live, clearly defining rights, obligations, and shared operating standards.",
    documentIncludes: [
      "Scope of partnership and service types",
      "Commercial terms and settlement cycle",
      "Quality standards and SLA",
      "Privacy policy and customer data protection",
      "Renewal and termination terms",
    ],
    signingSteps: [
      "WOS sends the draft MOU after verification is complete",
      "Both parties review and negotiate terms (if needed)",
      "Sign via e-signature or physical document",
      "Signed MOU is stored in your Partner Dashboard",
    ],
    downloadLabel: "Request a sample MOU",
    downloadNote: "Our team will email a sample document after initial verification is confirmed.",
  },
  responsibilitiesSla: {
    headline: "Responsibilities & SLA",
    intro: "A clear split of duties between WOS and partners, with agreed response-time standards.",
    responsibilities: [
      { area: "Marketing & lead generation", wos: "Source and pre-screen medical travelers", partner: "Provide accurate, up-to-date service information" },
      { area: "Booking & confirmation", wos: "Operate the booking platform", partner: "Confirm or decline booking requests within the agreed window" },
      { area: "Service quality", wos: "Monitor quality and collect user feedback", partner: "Deliver service to the standard agreed in the MOU" },
      { area: "Payments", wos: "Settle payments on the agreed cycle", partner: "Issue correct receipts / accounting documents" },
      { area: "Customer data", wos: "Protect data per the privacy policy", partner: "Use customer data only to fulfil bookings made via WOS" },
    ],
    slaHeadline: "Service Level Standards (SLA)",
    slaItems: [
      { label: "Booking confirmation", target: "Within 4 business hours" },
      { label: "Customer inquiry response", target: "Within 24 hours" },
      { label: "Urgent case escalation", target: "Within 1 hour" },
      { label: "Partner settlement cycle", target: "Within 30 days of billing cycle close" },
    ],
  },
  seo: {
    title: "Partner with WOS | Medical Tourism Partner Network",
    description: "Join WOS as a partner. A transparent, secure, and sustainable medical tourism ecosystem.",
    keywords: ["partner", "medical tourism", "WOS", "hospital", "clinic", "hotel", "transport"],
  },
  applyForm: {
    eyebrow: "PARTNER APPLICATION",
    headline: "Apply to Become a Founding Partner",
    subheadline: "Fill in the details below. Our team will review and reach out within 48 hours.",
    sections: {
      company: "Company Information",
      contact: "Contact Information",
      services: "Type & Services",
      consent: "Confirm Application",
    },
    fields: {
      companyName: "Company / establishment name",
      registrationNumber: "Business registration number",
      taxId: "Tax ID",
      businessType: "Business type",
      businessTypeOptions: [
        { value: "HOSPITAL", label: "Hospital" },
        { value: "CLINIC", label: "Specialty Clinic" },
        { value: "HOTEL", label: "Hotel & Accommodation" },
        { value: "TRANSPORT", label: "Transport Services" },
        { value: "CORPORATE", label: "Corporate & Investor" },
        { value: "WELLNESS_SPA", label: "Wellness & Spa" },
      ],
      yearEstablished: "Year established",
      employeeCount: "Number of employees",
      primaryName: "Primary contact name",
      primaryTitle: "Job title",
      primaryEmail: "Email",
      primaryPhone: "Phone number",
      primaryLineId: "Line ID",
      address: "Address",
      district: "District",
      province: "Province",
      postalCode: "Postal code",
      serviceTypes: "Services offered (select all that apply)",
      languages: "Languages supported",
      operatingHours: "Operating hours",
      capacity: "Capacity (e.g. beds / rooms / vehicles)",
    },
    consent: {
      acceptTerms: "I accept WOS's Partner Terms & Conditions",
      acceptPrivacy: "I accept WOS's Privacy Policy",
      acceptSLA: "I acknowledge and agree to comply with the defined SLA standards",
    },
    submitLabel: "Submit Application",
    submittingLabel: "Submitting...",
    successTitle: "Application submitted",
    successBody: "Thank you for your interest. The WOS team will contact you within 48 hours.",
    errorTitle: "Submission failed",
    errorBody: "Please try again, or contact our team directly if the issue persists.",
    validationError: "Please fill in all fields marked with *.",
  },
};
