// content/partner/en.ts
import type { PartnerPageContent } from "./types";

export const en: PartnerPageContent = {
  locale: "en",
  hero: {
    eyebrow: "WOS PARTNER NETWORK",
    boardingLabel: "PARTNER PASS",
    headline: "Reach Wellness & Healthcare Customers from Laos — Through WOS",
    subheadline:
      "WOS connects hospitals, clinics, wellness providers, and related services in Thailand with customers from Laos — helping manage the journey from discovery and booking through pre- and post-service coordination.",
    ctaText: "Become a Partner",
    ctaLink: "/partner/apply",
  },
  foundingPartner: {
    eyebrow: "WOS FOUNDING PARTNER PROGRAM",
    headline: "Become a WOS Founding Partner",
    intro:
      "WOS is opening its first cohort of partners to help build a cross-border Healthcare & Wellness network between Thailand and Laos. Founding Partners get hands-on onboarding and help shaping cross-border service packages with the WOS team.",
    benefitsHeadline: "Benefits",
    benefits: [
      "No setup fee during the Pilot",
      "No monthly platform fee during the Pilot",
      "Priority onboarding",
      "Help building service packages for Lao customers",
      "Partner profile on WOS",
      "Opportunity to receive cross-border leads",
      "Join the WOS network",
    ],
  },
  whyPartner: {
    headline: "Why Partner with WOS",
    reasons: [
      {
        code: "ACC",
        title: "Access the Lao Customer Market",
        description: "WOS is building a partner network for customers travelling to Thailand for healthcare and wellness services.",
        icon: "🎯",
      },
      {
        code: "REV",
        title: "Transparent Revenue Model",
        description: "Clear fee structure, no hidden costs. On-time monthly settlements.",
        icon: "💰",
      },
      {
        code: "TRU",
        title: "Build Credibility with WOS Trust Standard",
        description: "Official certification and listing. Featured in trusted Partner Directory.",
        icon: "⭐",
      },
      {
        code: "MGT",
        title: "Easy Management via Partner Dashboard",
        description: "Manage bookings, availability, and reports. Desktop & mobile friendly.",
        icon: "📊",
      },
    ],
  },
  partnerTypes: [
    {
      code: "HSP",
      name: "Hospitals",
      icon: "🏥",
      description: "General / Specialty / Medical Centers",
      subTypes: ["General Hospital", "Specialty Hospital", "Medical Center"],
      requirements: ["Valid License", "Specialist Doctors", "Safety Standards"],
    },
    {
      code: "CLN",
      name: "Specialty Clinics",
      icon: "🏪",
      description: "Dental / Aesthetic / Eye Care / etc.",
      subTypes: ["Dental", "Aesthetic", "Eye Care", "Physical Therapy"],
      requirements: ["Certified Professionals", "Standard Equipment", "Business License"],
    },
    {
      code: "HTL",
      name: "Hotels & Accommodation",
      icon: "🏨",
      description: "3-5 Star Hotels / Serviced Apartments",
      subTypes: ["3-Star Hotels", "4-Star Hotels", "5-Star Hotels", "Serviced Apartments"],
      requirements: ["Full Facilities", "Patient-friendly", "Cleanliness Standards"],
    },
    {
      code: "TRN",
      name: "Transport Services",
      icon: "🚗",
      description: "Ambulance / Patient Transfer / VIP Vans",
      subTypes: ["Ambulance", "Patient Transfer", "VIP Vans", "Limousine"],
      requirements: ["Insurance Coverage", "Professional Drivers", "Well-maintained Vehicles"],
    },
    {
      code: "COR",
      name: "Corporate & Investors",
      icon: "🏢",
      description: "Insurance Companies / DMCs / Developers",
      subTypes: ["Insurance", "DMC", "Project Developer", "Medical Consultant"],
      requirements: ["Industry Experience", "Financial Stability", "Network Support"],
    },
    {
      code: "WEL",
      name: "Wellness & Spa",
      icon: "🌿",
      description: "Spa / Thai Massage / Holistic Wellness Centers / Detox & Recovery",
      subTypes: ["Spa", "Thai Massage", "Wellness Center", "Detox & Recovery"],
      requirements: ["Valid Spa/Massage License", "Trained & Certified Staff", "Clean & Hygienic Facility"],
    },
  ],
  phaseFocus: {
    label: "WOS Founding Partner Focus",
    headline: "Phase 1: Clinic & Wellness",
    description: "WOS is currently focused on clinics, wellness providers, and healthcare providers well-positioned to serve customers from Laos.",
  },
  howItWorks: [
    { stepNumber: 1, title: "Apply", description: "Submit your business and service information to the WOS team.", duration: "48 hours" },
    { stepNumber: 2, title: "Partner Review", description: "WOS reviews your qualifications and discusses your business model.", duration: "3-5 days" },
    { stepNumber: 3, title: "Package Setup", description: "Work together to build service packages for Lao customers.", duration: "3-5 days" },
    { stepNumber: 4, title: "Pilot Agreement", description: "Agree on commercial terms and SLA together.", duration: "1-2 days" },
    { stepNumber: 5, title: "Go Live", description: "Launch on WOS and start receiving leads / bookings.", duration: "Immediate" },
  ],
  operatingModel: {
    headline: "How WOS Works",
    flowSteps: [
      "Traveler",
      "Search Services",
      "Compare Partners",
      "Book via WOS",
      "Receive Service",
      "WOS Quality Check",
      "Payment",
      "Follow-up",
    ],
    keyPoints: [
      "WOS acts as a trusted intermediary",
      "WOS verifies partner information and qualifications before onboarding, and tracks customer feedback",
      "Payments are coordinated on the agreed settlement cycle",
      "Continuous quality improvement through data & feedback",
    ],
  },
  benefits: [
    { title: "Comprehensive Management System", description: "Easy-to-use Partner Dashboard. Self-manage schedules, pricing & promotions.", icon: "✅", features: ["Schedule Management", "Self Pricing", "Promotions", "Booking History"] },
    { title: "Marketing & Promotion", description: "Featured in Partner Directory. Promoted via Social Media & Newsletter.", icon: "📢", features: ["Partner Directory", "Social Media Promotion", "Newsletter Feature", "WOS Trusted Partner Badge"] },
    { title: "WOS Partner Support", description: "The WOS team coordinates bookings and service delivery within the scope agreed with each partner.", icon: "💬", features: ["Booking coordination", "Thai/English", "Line / WhatsApp contact"] },
    { title: "Business Reporting & Booking Data", description: "See customer behavior and demand trends, plus sales and booking reports.", icon: "📊", features: ["Customer Insights", "Sales Reports", "Trend Analysis"] },
    { title: "Business Growth", description: "Cross-partner collaboration opportunities. Regional events and networking.", icon: "🤝", features: ["Cross-partner Projects", "Regional Events", "Networking", "Business Matching"] },
  ],
  commercialTerms: {
    headline: "Commercial Model",
    intro:
      "Performance-based Partnership — no setup fee and no monthly platform fee for Founding Partners during the pilot phase. WOS earns a service fee / commission on transactions, per the terms agreed in the Partner Agreement.",
    docStamp: "Founding Partner Terms",
    terms: [
      { label: "Setup fee", value: "None", note: "Founding Partners, during the Pilot" },
      { label: "Monthly platform fee", value: "None", note: "During the Pilot" },
      { label: "Commission / service fee", value: "Charged on actual transactions", note: "Per the terms agreed in the Partner Agreement" },
      { label: "Settlement cycle", value: "Monthly, within 30 days of billing cycle close" },
      { label: "Contract term", value: "1 year, auto-renews unless cancelled in advance" },
      { label: "Settlement currency", value: "THB / USD (by agreement)" },
    ],
    disclaimer: "Full commission and contract terms are set out in the signed Pilot Agreement / MOU.",
  },
  mou: {
    headline: "MOU & Partnership Agreement",
    intro:
      "Every WOS partner signs a Memorandum of Understanding (MOU) before going live, clearly defining rights, obligations, and shared operating standards.",
    documentIncludes: [
      "Scope of partnership and service types",
      "Commercial terms and settlement cycle",
      "Quality standards and SLA",
      "Privacy policy and customer data protection",
      "Renewal and termination terms",
    ],
    signingSteps: [
      "WOS sends the draft MOU after verification is complete",
      "Both parties review and negotiate terms (if needed)",
      "Sign via e-signature or physical document",
      "Signed MOU is stored in your Partner Dashboard",
    ],
    downloadLabel: "Request a sample MOU",
    downloadNote: "Our team will email a sample document after initial verification is confirmed.",
  },
  responsibilitiesSla: {
    headline: "Responsibilities & SLA",
    intro: "A clear split of duties between WOS and partners, with agreed response-time standards.",
    responsibilities: [
      { area: "Marketing & lead generation", wos: "Source and pre-screen medical travelers", partner: "Provide accurate, up-to-date service information" },
      { area: "Booking & confirmation", wos: "Operate the booking platform", partner: "Confirm or decline booking requests within the agreed window" },
      { area: "Service quality", wos: "Monitor quality and collect user feedback", partner: "Deliver service to the standard agreed in the MOU" },
      { area: "Payments", wos: "Settle payments on the agreed cycle", partner: "Issue correct receipts / accounting documents" },
      { area: "Customer data", wos: "Protect data per the privacy policy", partner: "Use customer data only to fulfil bookings made via WOS" },
    ],
    slaHeadline: "Service Level Standards (SLA)",
    slaItems: [
      { label: "Booking confirmation", target: "Within 4 business hours" },
      { label: "Customer inquiry response", target: "Within 24 hours" },
      { label: "Urgent case escalation", target: "Within 1 hour" },
      { label: "Partner settlement cycle", target: "Within 30 days of billing cycle close" },
    ],
  },
  prepare: {
    eyebrow: "PARTNER CHECKLIST",
    headline: "What Partners Need to Prepare",
    items: [
      "Company / business information",
      "Relevant licenses",
      "Service list",
      "Pricing",
      "Photos of services / venue",
      "Availability",
      "Cancellation policy",
      "Primary contact",
      "Payment information",
      "Service package for international customers",
    ],
    ctaText: "Start Your WOS Founding Partner Application",
    ctaLink: "/partner/apply",
  },
  cta: {
    headline: "Ready to Grow Together?",
    subtext: "Start your partnership with WOS today. Click below and our team will reach out within 48 hours.",
    buttonText: "Become a Partner →",
    buttonLink: "/partner/apply",
    gateLabel: "BOARDING NOW",
  },
  seo: {
    title: "Partner with WOS | Medical Tourism Partner Network",
    description: "Join WOS as a partner. A transparent, secure, and sustainable medical tourism ecosystem.",
    keywords: ["partner", "medical tourism", "WOS", "hospital", "clinic", "hotel", "transport"],
  },
  applyForm: {
    eyebrow: "PARTNER APPLICATION",
    headline: "Apply to Become a WOS Partner",
    subheadline: "Fill in the details below. Our team will review and reach out within 48 hours.",
    sections: {
      company: "Company Information",
      contact: "Contact Information",
      services: "Type & Services",
      consent: "Confirm Application",
    },
    fields: {
      companyName: "Company / establishment name",
      registrationNumber: "Business registration number",
      taxId: "Tax ID",
      businessType: "Business type",
      businessTypeOptions: [
        { value: "HOSPITAL", label: "Hospital" },
        { value: "CLINIC", label: "Specialty Clinic" },
        { value: "HOTEL", label: "Hotel & Accommodation" },
        { value: "TRANSPORT", label: "Transport Services" },
        { value: "CORPORATE", label: "Corporate & Investor" },
        { value: "WELLNESS_SPA", label: "Wellness & Spa" },
      ],
      yearEstablished: "Year established",
      employeeCount: "Number of employees",
      primaryName: "Primary contact name",
      primaryTitle: "Job title",
      primaryEmail: "Email",
      primaryPhone: "Phone number",
      primaryLineId: "Line ID",
      address: "Address",
      district: "District",
      province: "Province",
      postalCode: "Postal code",
      serviceTypes: "Services offered (select all that apply)",
      languages: "Languages supported",
      operatingHours: "Operating hours",
      capacity: "Capacity (e.g. beds / rooms / vehicles)",
    },
    consent: {
      acceptTerms: "I accept WOS's Partner Terms & Conditions",
      acceptPrivacy: "I accept WOS's Privacy Policy",
      acceptSLA: "I acknowledge and agree to comply with the defined SLA standards",
    },
    submitLabel: "Submit Application",
    submittingLabel: "Submitting...",
    successTitle: "Application submitted",
    successBody: "Thank you for your interest. The WOS team will contact you within 48 hours.",
    errorTitle: "Submission failed",
    errorBody: "Please try again, or contact our team directly if the issue persists.",
    validationError: "Please fill in all fields marked with *.",
  },
};
