// content/partner/lo.ts
//
// ⚠️ TRANSLATION REVIEW NOTE:
// The original DeepSeek export only contained Thai and English content.
// The Lao text below is a best-effort translation produced for this build —
// it has NOT been proofread by a native Lao speaker. Please have someone on
// your Lao-market team (or a professional translator) review this file
// before publishing, the same way you'd want any legal/commercial copy checked.
//
import type { PartnerPageContent } from "./types";

export const lo: PartnerPageContent = {
  locale: "lo",
  hero: {
    eyebrow: "WOS PARTNER NETWORK",
    boardingLabel: "PARTNER PASS",
    headline: "ເຂົ້າເຖິງລູກຄ້າສຸຂະພາບ ແລະ Wellness ຈາກລາວ ຜ່ານ WOS",
    subheadline:
      "WOS ຊ່ວຍເຊື່ອມຕໍ່ໂຮງໝໍ ຄລີນິກ Wellness ແລະ ບໍລິການທີ່ກ່ຽວຂ້ອງໃນປະເທດໄທກັບລູກຄ້າຈາກລາວ ພ້ອມຊ່ວຍຈັດການ Journey ຕັ້ງແຕ່ການຄົ້ນຫາບໍລິການ ການຈອງ ຈົນເຖິງການປະສານງານກ່ອນ ແລະ ຫຼັງຮັບບໍລິການ",
    ctaText: "ເປັນຄູ່ຮ່ວມທຸລະກິດກັບພວກເຮົາ",
    ctaLink: "/partner/apply",
  },
  foundingPartner: {
    eyebrow: "WOS FOUNDING PARTNER PROGRAM",
    headline: "ເປັນໜຶ່ງໃນ WOS Founding Partners",
    intro:
      "WOS ກຳລັງເປີດຮັບຄູ່ຮ່ວມທຸລະກິດຮຸ່ນທຳອິດ ເພື່ອຮ່ວມສ້າງເຄືອຂ່າຍ Healthcare & Wellness ລະຫວ່າງປະເທດໄທ ແລະ ລາວ ຄູ່ຮ່ວມທຸລະກິດຮຸ່ນທຳອິດຈະໄດ້ຮັບການ Onboarding ແລະ ຊ່ວຍຈັດທຳ Cross-border Service Packages ຮ່ວມກັບທີມ WOS",
    benefitsHeadline: "ສິດທິປະໂຫຍດ",
    benefits: [
      "ບໍ່ມີຄ່າ Setup ໃນຊ່ວງ Pilot",
      "ບໍ່ມີ Monthly Platform Fee ໃນຊ່ວງ Pilot",
      "Priority Onboarding",
      "ຊ່ວຍຈັດທຳ Service Packages ສຳລັບລູກຄ້າລາວ",
      "Partner Profile ຢູ່ໃນ WOS",
      "ໂອກາດຮັບ Cross-border Leads",
      "ເຂົ້າຮ່ວມເຄືອຂ່າຍ WOS",
    ],
  },
  whyPartner: {
    headline: "ເປັນຫຍັງການຮ່ວມມືກັບ WOS ຈຶ່ງເປີດໂອກາດທຸລະກິດຫຼາຍກວ່າ",
    reasons: [
      {
        code: "ACC",
        title: "ເຂົ້າເຖິງຕະຫຼາດລູກຄ້າຈາກລາວ",
        description: "WOS ກຳລັງສ້າງເຄືອຂ່າຍຄູ່ຮ່ວມທຸລະກິດສຳລັບລູກຄ້າທີ່ຕ້ອງການເດີນທາງມາຮັບບໍລິການສຸຂະພາບ ແລະ Wellness ໃນປະເທດໄທ",
        icon: "🎯",
      },
      {
        code: "REV",
        title: "ເພີ່ມລາຍຮັບດ້ວຍລະບົບທີ່ໂປ່ງໃສ",
        description: "ຄ່າທຳນຽມທີ່ຊັດເຈນ ບໍ່ມີຄ່າແອບແຝງ ຈ່າຍເງິນຕົງເວລາທຸກເດືອນ",
        icon: "💰",
      },
      {
        code: "TRU",
        title: "ສ້າງຄວາມໜ້າເຊື່ອຖືດ້ວຍ WOS Trust Standard",
        description: "ໄດ້ຮັບການຮັບຮອງຈາກ WOS Trust Standard ປາກົດຢູ່ໃນ Partner Directory ທີ່ຜູ້ໃຊ້ໄວ້ວາງໃຈ",
        icon: "⭐",
      },
      {
        code: "MGT",
        title: "ບໍລິຫານຈັດການງ່າຍດ້ວຍ Partner Dashboard",
        description: "ຈັດການການຈອງ ອັບເດດຕາຕະລາງເວລາ ເບິ່ງລາຍງານຍ້ອນຫຼັງ ຮອງຮັບທັງເດັສທັອບ ແລະ ມືຖື",
        icon: "📊",
      },
    ],
  },
  partnerTypes: [
    {
      code: "HSP",
      name: "ໂຮງໝໍ",
      icon: "🏥",
      description: "ໂຮງໝໍທົ່ວໄປ / ໂຮງໝໍສະເພາະທາງ / ສູນການແພດ",
      subTypes: ["ໂຮງໝໍທົ່ວໄປ", "ໂຮງໝໍສະເພາະທາງ", "ສູນການແພດ"],
      requirements: ["ມີໃບອະນຸຍາດດຳເນີນການ", "ມີທ່ານໝໍຊ່ຽວຊານ", "ຜ່ານມາດຕະຖານຄວາມປອດໄພ"],
    },
    {
      code: "CLN",
      name: "ຄລີນິກສະເພາະທາງ",
      icon: "🏪",
      description: "ຄລີນິກແຂ້ວ / ຄລີນິກຄວາມງາມ / ຄລີນິກຕາ ແລະ ອື່ນໆ",
      subTypes: ["ແຂ້ວ", "ຄວາມງາມ", "ຕາ", "ກາຍະພາບບຳບັດ"],
      requirements: ["ມີທ່ານໝໍປະຈຳ", "ອຸປະກອນມາດຕະຖານ", "ໃບອະນຸຍາດດຳເນີນກິດຈະການ"],
    },
    {
      code: "HTL",
      name: "ໂຮງແຮມ ແລະ ທີ່ພັກ",
      icon: "🏨",
      description: "ໂຮງແຮມ 3-5 ດາວ / ເຊີວິດອາພາດເມັນ",
      subTypes: ["ໂຮງແຮມ 3 ດາວ", "ໂຮງແຮມ 4 ດາວ", "ໂຮງແຮມ 5 ດາວ", "ເຊີວິດອາພາດເມັນ"],
      requirements: ["ສິ່ງອຳນວຍຄວາມສະດວກຄົບຖ້ວນ", "ຮອງຮັບຄົນເຈັບ ແລະ ຍາດພີ່ນ້ອງ", "ມີມາດຕະຖານຄວາມສະອາດ"],
    },
    {
      code: "TRN",
      name: "ບໍລິການຮັບສົ່ງ",
      icon: "🚗",
      description: "ລົດໂຮງໝໍ / ລົດຮັບສົ່ງຄົນເຈັບ / ລົດຕູ້ VIP",
      subTypes: ["ລົດໂຮງໝໍ", "ລົດຮັບສົ່ງຄົນເຈັບ", "ລົດຕູ້ VIP", "ລົດລີມູຊີນ"],
      requirements: ["ມີປະກັນໄພ", "ພະນັກງານຂັບລົດມືອາຊີບ", "ລົດສະພາບດີພ້ອມໃຊ້ງານ"],
    },
    {
      code: "COR",
      name: "ອົງກອນ ແລະ ນັກລົງທຶນ",
      icon: "🏢",
      description: "ບໍລິສັດປະກັນໄພ / DMC / ຜູ້ພັດທະນາໂຄງການ",
      subTypes: ["ບໍລິສັດປະກັນໄພ", "DMC", "ຜູ້ພັດທະນາໂຄງການ", "ທີ່ປຶກສາທາງການແພດ"],
      requirements: ["ມີປະສົບການໃນອຸດສາຫະກຳ", "ຖານະການເງິນໝັ້ນຄົງ", "ພ້ອມສະໜັບສະໜູນການຂະຫຍາຍເຄືອຂ່າຍ"],
    },
    {
      code: "WEL",
      name: "ບໍລິການ Wellness ແລະ ສະປາ",
      icon: "🌿",
      description: "ສະປາ / ນວດແຜນໄທ / ສູນສຸຂະພາບລວມ / ດີທັອກ ແລະ ຟື້ນຟູຮ່າງກາຍ",
      subTypes: ["ສະປາ", "ນວດແຜນໄທ", "ສູນເວວເນສ", "ດີທັອກ/ຟື້ນຟູຮ່າງກາຍ"],
      requirements: ["ມີໃບອະນຸຍາດດຳເນີນກິດຈະການສະປາ/ນວດ", "ພະນັກງານຜ່ານການຝຶກອົບຮົມມາດຕະຖານ", "ສະຖານທີ່ສະອາດຖືກສຸຂະລັກສະນະ"],
    },
  ],
  phaseFocus: {
    label: "WOS Founding Partner Focus",
    headline: "Phase 1: Clinic & Wellness",
    description: "WOS ກຳລັງໃຫ້ຄວາມສຳຄັນກັບ Clinic, Wellness ແລະ Healthcare Providers ທີ່ມີສັກກະຍະພາບໃນການໃຫ້ບໍລິການລູກຄ້າຈາກລາວ",
  },
  howItWorks: [
    { stepNumber: 1, title: "Apply", description: "ສົ່ງຂໍ້ມູນທຸລະກິດ ແລະ ບໍລິການໃຫ້ທີມ WOS", duration: "48 ຊົ່ວໂມງ" },
    { stepNumber: 2, title: "Partner Review", description: "WOS ກວດສອບຄຸນສົມບັດ ແລະ ເວົ້າລົມຮູບແບບທຸລະກິດຮ່ວມກັນ", duration: "3-5 ວັນ" },
    { stepNumber: 3, title: "Package Setup", description: "ຮ່ວມກັນຈັດທຳ Service / Package ສຳລັບລູກຄ້າຈາກລາວ", duration: "3-5 ວັນ" },
    { stepNumber: 4, title: "Pilot Agreement", description: "ຕົກລົງ Commercial Terms ແລະ SLA ຮ່ວມກັນ", duration: "1-2 ວັນ" },
    { stepNumber: 5, title: "Go Live", description: "ເປີດບໍລິການເທິງ WOS ແລະ ເລີ່ມຮັບ Lead / Booking", duration: "ທັນທີ" },
  ],
  operatingModel: {
    headline: "WOS ເຮັດວຽກແນວໃດ",
    flowSteps: [
      "ນັກທ່ອງທ່ຽວ",
      "ຄົ້ນຫາບໍລິການ",
      "ປຽບທຽບຄູ່ຮ່ວມທຸລະກິດ",
      "ຈອງຜ່ານ WOS",
      "ຮັບບໍລິການຈາກຄູ່ຮ່ວມທຸລະກິດ",
      "WOS ກວດສອບຄຸນນະພາບ",
      "ຈ່າຍເງິນ",
      "ຕິດຕາມຜົນ",
    ],
    keyPoints: [
      "WOS ເຮັດໜ້າທີ່ເປັນຕົວກາງທີ່ເຊື່ອຖືໄດ້ (Trusted Intermediary)",
      "WOS ມີຂັ້ນຕອນກວດສອບຂໍ້ມູນ ແລະ ຄຸນສົມບັດຂອງຄູ່ຮ່ວມທຸລະກິດກ່ອນເຂົ້າຮ່ວມເຄືອຂ່າຍ ແລະ ຕິດຕາມ Feedback ຈາກລູກຄ້າ",
      "ປະສານການຈ່າຍເງິນຕາມຮອບບິນທີ່ຕົກລົງຮ່ວມກັນ",
      "ເກັບຂໍ້ມູນ ແລະ Feedback ເພື່ອພັດທະນາຄຸນນະພາບຢ່າງຕໍ່ເນື່ອງ",
    ],
  },
  benefits: [
    { title: "ລະບົບບໍລິຫານຈັດການຄົບວົງຈອນ", description: "Partner Dashboard ໃຊ້ງານງ່າຍ ຈັດການຕາຕະລາງເວລາ ລາຄາ ແລະ ໂປຣໂມຊັນໄດ້ເອງ", icon: "✅", features: ["ຈັດການຕາຕະລາງເວລາ", "ປັບລາຄາໄດ້ເອງ", "ສ້າງໂປຣໂມຊັນ", "ເບິ່ງປະຫວັດການຈອງ"] },
    { title: "ການຕະຫຼາດ ແລະ ໂປຣໂມດ", description: "ປາກົດຢູ່ໃນ Partner Directory ໄດ້ຮັບການໂປຣໂມດຜ່ານ Social Media ແລະ Newsletter", icon: "📢", features: ["Partner Directory", "ໂປຣໂມດຜ່ານ Social Media", "ຂຶ້ນ Newsletter", "ຕາ WOS Trusted Partner"] },
    { title: "WOS Partner Support", description: "ທີມ WOS ຊ່ວຍປະສານງານດ້ານການຈອງ ແລະ ການໃຫ້ບໍລິການຕາມຂອບເຂດທີ່ຕົກລົງກັບຄູ່ຮ່ວມທຸລະກິດ", icon: "💬", features: ["ປະສານງານການຈອງ", "ໄທ/ອັງກິດ", "ຕິດຕໍ່ຜ່ານ Line / WhatsApp"] },
    { title: "ລາຍງານທຸລະກິດ ແລະ ຂໍ້ມູນການຈອງ", description: "ເບິ່ງພຶດຕິກຳ ແລະ ຄວາມຕ້ອງການຂອງລູກຄ້າ ພ້ອມລາຍງານຍອດຂາຍ ແລະ ແນວໂນ້ມການຈອງ", icon: "📊", features: ["ຂໍ້ມູນພຶດຕິກຳລູກຄ້າ", "ລາຍງານຍອດຂາຍ", "ວິເຄາະແນວໂນ້ມ"] },
    { title: "ການຕໍ່ຍອດທຸລະກິດ", description: "ໂອກາດຮ່ວມໂຄງການກັບຄູ່ຮ່ວມທຸລະກິດລາຍອື່ນ ເຂົ້າຮ່ວມກິດຈະກຳ ແລະ ເຄືອຂ່າຍລະດັບພາກພື້ນ", icon: "🤝", features: ["ໂຄງການຮ່ວມຄູ່ຮ່ວມທຸລະກິດ", "ກິດຈະກຳລະດັບພາກພື້ນ", "ສ້າງເຄືອຂ່າຍ", "ຈັບຄູ່ທຸລະກິດ"] },
  ],
  commercialTerms: {
    headline: "Commercial Model",
    intro:
      "Performance-based Partnership — WOS ບໍ່ມີຄ່າ Setup ແລະ ບໍ່ມີ Monthly Platform Fee ສຳລັບ Founding Partner ໃນຊ່ວງ Pilot WOS ຈະໄດ້ຮັບຄ່າບໍລິການ/Commission ເມື່ອເກີດທຸລະກຳ ຕາມເງື່ອນໄຂທີ່ຕົກລົງຮ່ວມກັນໃນ Partner Agreement",
    docStamp: "Founding Partner Terms",
    terms: [
      { label: "ຄ່າ Setup", value: "ບໍ່ມີ", note: "ສຳລັບ Founding Partner ໃນຊ່ວງ Pilot" },
      { label: "Monthly Platform Fee", value: "ບໍ່ມີ", note: "ໃນຊ່ວງ Pilot" },
      { label: "ຄ່າຄອມມິຊັນ / ຄ່າບໍລິການ", value: "ຄິດຕາມທຸລະກຳຈິງ", note: "ຕາມເງື່ອນໄຂທີ່ຕົກລົງຮ່ວມກັນໃນ Partner Agreement" },
      { label: "ຮອບການຈ່າຍເງິນ", value: "ລາຍເດືອນ ພາຍໃນ 30 ວັນຫຼັງປິດຮອບບິນ" },
      { label: "ໄລຍະເວລາສັນຍາ", value: "1 ປີ ຕໍ່ອາຍຸອັດຕະໂນມັດ ເວັ້ນເສຍແຕ່ແຈ້ງຍົກເລີກລ່ວງໜ້າ" },
      { label: "ສະກຸນເງິນທີ່ຈ່າຍ", value: "THB / USD (ຕາມຂໍ້ຕົກລົງ)" },
    ],
    disclaimer: "ລາຍລະອຽດຄ່າຄອມມິຊັນ ແລະ ເງື່ອນໄຂສະບັບສົມບູນຈະລະບຸໄວ້ໃນ Pilot Agreement / MOU ທີ່ລົງນາມຮ່ວມກັນ",
  },
  mou: {
    headline: "MOU ແລະ ຂໍ້ຕົກລົງຄວາມຮ່ວມມື",
    intro:
      "ຄູ່ຮ່ວມທຸລະກິດທຸກລາຍຂອງ WOS ຈະລົງນາມໃນບົດບັນທຶກຄວາມເຂົ້າໃຈ (MOU) ກ່ອນເລີ່ມໃຫ້ບໍລິການ ເພື່ອກຳນົດສິດ ໜ້າທີ່ ແລະ ມາດຕະຖານການເຮັດວຽກຮ່ວມກັນຢ່າງຊັດເຈນ",
    documentIncludes: [
      "ຂອບເຂດຄວາມຮ່ວມມື ແລະ ປະເພດບໍລິການ",
      "ເງື່ອນໄຂທາງການຄ້າ ແລະ ຮອບການຈ່າຍເງິນ",
      "ມາດຕະຖານຄຸນນະພາບ ແລະ SLA",
      "ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ ແລະ ການປົກປ້ອງຂໍ້ມູນລູກຄ້າ",
      "ເງື່ອນໄຂການຕໍ່ອາຍຸ ແລະ ການຍົກເລີກສັນຍາ",
    ],
    signingSteps: [
      "ທີມ WOS ສົ່ງຮ່າງ MOU ຫຼັງຈາກຜ່ານການກວດສອບຄຸນສົມບັດ",
      "ທັງສອງຝ່າຍທົບທວນ ແລະ ເຈລະຈາເງື່ອນໄຂ (ຖ້າມີ)",
      "ລົງນາມຜ່ານລະບົບລົງນາມເອເລັກໂຕຣນິກ ຫຼື ເອກະສານຕົ້ນສະບັບ",
      "ຈັດເກັບສຳເນົາ MOU ໄວ້ໃນລະບົບ Partner Dashboard ຂອງທ່ານ",
    ],
    downloadLabel: "ຂໍຕົວຢ່າງຮ່າງ MOU",
    downloadNote: "ທີມງານຈະສົ່ງຕົວຢ່າງເອກະສານໃຫ້ທາງອີເມວຫຼັງຈາກຢືນຢັນຄຸນສົມບັດເບື້ອງຕົ້ນ",
  },
  responsibilitiesSla: {
    headline: "ຄວາມຮັບຜິດຊອບ ແລະ SLA",
    intro: "ແບ່ງບົດບາດໜ້າທີ່ລະຫວ່າງ WOS ແລະ ຄູ່ຮ່ວມທຸລະກິດໃຫ້ຊັດເຈນ ພ້ອມມາດຕະຖານເວລາຕອບສະໜອງທີ່ຕົກລົງຮ່ວມກັນ",
    responsibilities: [
      { area: "ການຕະຫຼາດ ແລະ ຫາລູກຄ້າ", wos: "ຈັດຫາ ແລະ ຄັດກອງນັກທ່ອງທ່ຽວເຊີງການແພດ", partner: "ໃຫ້ຂໍ້ມູນບໍລິການທີ່ຖືກຕ້ອງ ແລະ ທັນສະໄໝ" },
      { area: "ການຈອງ ແລະ ຢືນຢັນ", wos: "ຈັດການລະບົບຈອງຜ່ານແພລດຟອມ", partner: "ຢືນຢັນ ຫຼື ປະຕິເສດຄຳຮ້ອງຂໍຈອງພາຍໃນເວລາທີ່ກຳນົດ" },
      { area: "ຄຸນນະພາບບໍລິການ", wos: "ກວດສອບຄຸນນະພາບ ແລະ ຮັບ Feedback ຈາກຜູ້ໃຊ້", partner: "ໃຫ້ບໍລິການຕາມມາດຕະຖານທີ່ຕົກລົງໄວ້ໃນ MOU" },
      { area: "ການຈ່າຍເງິນ", wos: "ໂອນເງິນຕາມຮອບບິນທີ່ກຳນົດ", partner: "ອອກໃບຮັບເງິນ/ເອກະສານບັນຊີທີ່ຖືກຕ້ອງ" },
      { area: "ຂໍ້ມູນລູກຄ້າ", wos: "ປົກປ້ອງຂໍ້ມູນຕາມນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ", partner: "ໃຊ້ຂໍ້ມູນລູກຄ້າສະເພາະເພື່ອການໃຫ້ບໍລິການທີ່ຈອງຜ່ານ WOS" },
    ],
    slaHeadline: "ມາດຕະຖານເວລາຕອບສະໜອງ (SLA)",
    slaItems: [
      { label: "ຢືນຢັນການຈອງ", target: "ພາຍໃນ 4 ຊົ່ວໂມງເຮັດວຽກ" },
      { label: "ຕອບຄຳຖາມລູກຄ້າ", target: "ພາຍໃນ 24 ຊົ່ວໂມງ" },
      { label: "ແຈ້ງບັນຫາຮີບດ່ວນ (Urgent Case)", target: "ພາຍໃນ 1 ຊົ່ວໂມງ" },
      { label: "ຮອບການຈ່າຍເງິນຄູ່ຮ່ວມທຸລະກິດ", target: "ພາຍໃນ 30 ວັນຫຼັງປິດຮອບບິນ" },
    ],
  },
  prepare: {
    eyebrow: "PARTNER CHECKLIST",
    headline: "ຄູ່ຮ່ວມທຸລະກິດຕ້ອງກຽມຫຍັງແດ່",
    items: [
      "ຂໍ້ມູນບໍລິສັດ / ທຸລະກິດ",
      "ໃບອະນຸຍາດທີ່ກ່ຽວຂ້ອງ",
      "ລາຍການບໍລິການ",
      "ລາຄາ",
      "ຮູບພາບບໍລິການ / ສະຖານທີ່",
      "ຕາຕະລາງເວລາທີ່ໃຫ້ບໍລິການໄດ້",
      "ນະໂຍບາຍການຍົກເລີກ",
      "ຜູ້ຕິດຕໍ່ຫຼັກ",
      "ຂໍ້ມູນການຮັບຊຳລະເງິນ",
      "Service Package ສຳລັບລູກຄ້າຕ່າງປະເທດ",
    ],
    ctaText: "ເລີ່ມສະໝັກເປັນ WOS Founding Partner",
    ctaLink: "/partner/apply",
  },
  cta: {
    headline: "ພ້ອມທີ່ຈະເຕີບໂຕໄປນຳກັນແລ້ວບໍ?",
    subtext: "ເລີ່ມຕົ້ນຄວາມຮ່ວມມືກັບ WOS ມື້ນີ້ ພຽງແຕ່ກົດປຸ່ມຂ້າງລຸ່ມ ທີມງານຂອງພວກເຮົາຈະຕິດຕໍ່ຫາທ່ານພາຍໃນ 48 ຊົ່ວໂມງ",
    buttonText: "ເລີ່ມຕົ້ນເປັນຄູ່ຮ່ວມທຸລະກິດ →",
    buttonLink: "/partner/apply",
    gateLabel: "BOARDING NOW",
  },
  seo: {
    title: "ເປັນຄູ່ຮ່ວມທຸລະກິດກັບ WOS | Medical Tourism Partner Network",
    description: "ຮ່ວມເປັນຄູ່ຮ່ວມທຸລະກິດກັບ WOS ລະບົບນິເວດການທ່ອງທ່ຽວເຊີງການແພດທີ່ໂປ່ງໃສ ປອດໄພ ແລະ ເຕີບໂຕຢ່າງຍືນຍົງ",
    keywords: ["ຄູ່ຮ່ວມທຸລະກິດ", "ການທ່ອງທ່ຽວເຊີງການແພດ", "WOS", "ໂຮງໝໍ", "ຄລີນິກ", "ໂຮງແຮມ", "ບໍລິການຮັບສົ່ງ"],
  },
  applyForm: {
    eyebrow: "PARTNER APPLICATION",
    headline: "ສະໝັກເປັນຄູ່ຮ່ວມທຸລະກິດກັບ WOS",
    subheadline: "ປ້ອນຂໍ້ມູນຂ້າງລຸ່ມ ທີມງານຈະກວດສອບ ແລະ ຕິດຕໍ່ກັບພາຍໃນ 48 ຊົ່ວໂມງ",
    sections: {
      company: "ຂໍ້ມູນອົງກອນ",
      contact: "ຂໍ້ມູນຜູ້ຕິດຕໍ່",
      services: "ປະເພດ ແລະ ບໍລິການ",
      consent: "ຢືນຢັນການສະໝັກ",
    },
    fields: {
      companyName: "ຊື່ອົງກອນ / ສະຖານປະກອບການ",
      registrationNumber: "ເລກທະບຽນນິຕິບຸກຄົນ",
      taxId: "ເລກປະຈຳຕົວຜູ້ເສຍພາສີ",
      businessType: "ປະເພດທຸລະກິດ",
      businessTypeOptions: [
        { value: "HOSPITAL", label: "ໂຮງໝໍ" },
        { value: "CLINIC", label: "ຄລີນິກສະເພາະທາງ" },
        { value: "HOTEL", label: "ໂຮງແຮມ ແລະ ທີ່ພັກ" },
        { value: "TRANSPORT", label: "ບໍລິການຮັບສົ່ງ" },
        { value: "CORPORATE", label: "ອົງກອນ ແລະ ນັກລົງທຶນ" },
        { value: "WELLNESS_SPA", label: "ບໍລິການ Wellness ແລະ ສະປາ" },
      ],
      yearEstablished: "ປີກໍ່ຕັ້ງ",
      employeeCount: "ຈຳນວນພະນັກງານ",
      primaryName: "ຊື່ຜູ້ຕິດຕໍ່ຫຼັກ",
      primaryTitle: "ຕຳແໜ່ງ",
      primaryEmail: "ອີເມວ",
      primaryPhone: "ເບີໂທລະສັບ",
      primaryLineId: "Line ID",
      address: "ທີ່ຢູ່",
      district: "ເມືອງ/ຕົວເມືອງ",
      province: "ແຂວງ",
      postalCode: "ລະຫັດໄປສະນີ",
      serviceTypes: "ບໍລິການທີ່ໃຫ້ (ເລືອກໄດ້ຫຼາຍກວ່າ 1)",
      languages: "ພາສາທີ່ໃຫ້ບໍລິການ",
      operatingHours: "ເວລາເຮັດວຽກ",
      capacity: "ຄວາມສາມາດຮອງຮັບ (ເຊັ່ນ: ຈຳນວນຕຽງ/ຫ້ອງ/ຄັນ)",
    },
    consent: {
      acceptTerms: "ຂ້າພະເຈົ້າຍອມຮັບຂໍ້ກຳນົດ ແລະ ເງື່ອນໄຂການເປັນຄູ່ຮ່ວມທຸລະກິດຂອງ WOS",
      acceptPrivacy: "ຂ້າພະເຈົ້າຍອມຮັບນະໂຍບາຍຄວາມເປັນສ່ວນຕົວຂອງ WOS",
      acceptSLA: "ຂ້າພະເຈົ້າຮັບຊາບ ແລະ ຍິນຍອມປະຕິບັດຕາມມາດຕະຖານ SLA ທີ່ກຳນົດ",
    },
    submitLabel: "ສົ່ງໃບສະໝັກ",
    submittingLabel: "ກຳລັງສົ່ງຂໍ້ມູນ...",
    successTitle: "ສົ່ງໃບສະໝັກສຳເລັດ",
    successBody: "ຂອບໃຈສຳລັບຄວາມສົນໃຈ ທີມງານ WOS ຈະຕິດຕໍ່ກັບພາຍໃນ 48 ຊົ່ວໂມງ",
    errorTitle: "ສົ່ງໃບສະໝັກບໍ່ສຳເລັດ",
    errorBody: "ກະລຸນາລອງໃໝ່ອີກຄັ້ງ ຫຼື ຕິດຕໍ່ທີມງານໂດຍກົງຖ້າບັນຫາຍັງເກີດຂຶ້ນ",
  },
};
