// content/partner/th.ts
import type { PartnerPageContent } from "./types";

export const th: PartnerPageContent = {
  locale: "th",
  hero: {
    eyebrow: "WOS PARTNER NETWORK",
    boardingLabel: "PARTNER PASS",
    headline: "เข้าถึงลูกค้าสุขภาพและ Wellness จากลาว ผ่าน WOS",
    subheadline:
      "WOS ช่วยเชื่อมโรงพยาบาล คลินิก Wellness และบริการที่เกี่ยวข้องในประเทศไทยกับลูกค้าจากลาว พร้อมช่วยจัดการ Journey ตั้งแต่การค้นหาบริการ การจอง ไปจนถึงการประสานงานก่อนและหลังรับบริการ",
    ctaText: "ร่วมเป็นพาร์ทเนอร์กับ WOS",
    ctaLink: "/partner/apply",
  },
  foundingPartner: {
    eyebrow: "WOS FOUNDING PARTNER PROGRAM",
    headline: "เป็นหนึ่งใน WOS Founding Partners",
    intro:
      "WOS กำลังเปิดรับ Partner รุ่นแรกเพื่อร่วมสร้างเครือข่าย Healthcare & Wellness ระหว่างประเทศไทยและลาว Partner รุ่นแรกจะได้รับการ Onboarding และช่วยจัดทำ Cross-border Service Packages ร่วมกับทีม WOS",
    benefitsHeadline: "สิทธิประโยชน์",
    benefits: [
      "ไม่มีค่า Setup ในช่วง Pilot",
      "ไม่มี Monthly Platform Fee ในช่วง Pilot",
      "Priority Onboarding",
      "ช่วยจัดทำ Service Packages สำหรับลูกค้าลาว",
      "Partner Profile บน WOS",
      "โอกาสรับ Cross-border Leads",
      "เข้าร่วมเครือข่าย WOS",
    ],
  },
  whyPartner: {
    headline: "เพราะความร่วมมือกับ WOS เปิดโอกาสทางธุรกิจที่มากกว่า",
    reasons: [
      {
        code: "ACC",
        title: "เข้าถึงตลาดลูกค้าจากลาว",
        description:
          "WOS กำลังสร้างเครือข่าย Partner สำหรับลูกค้าที่ต้องการเดินทางมารับบริการสุขภาพและ Wellness ในประเทศไทย",
        icon: "🎯",
      },
      {
        code: "REV",
        title: "เพิ่มรายได้ด้วยระบบที่โปร่งใส",
        description: "ค่าธรรมเนียมที่ชัดเจน ไม่มีค่าซ่อนเร้น ชำระเงินตรงเวลา ทุกเดือน",
        icon: "💰",
      },
      {
        code: "TRU",
        title: "สร้างความน่าเชื่อถือด้วย Standard ที่ชัดเจน",
        description: "ได้รับการรับรองจาก WOS Trust Standard ปรากฏใน Partner Directory ที่ผู้ใช้ไว้วางใจ",
        icon: "⭐",
      },
      {
        code: "MGT",
        title: "บริหารจัดการง่ายด้วย Partner Dashboard",
        description: "จัดการการจอง อัปเดตตารางเวลา ดูรายงานย้อนหลัง รองรับทั้งเดสก์ท็อปและมือถือ",
        icon: "📊",
      },
    ],
  },
  partnerTypes: [
    {
      code: "HSP",
      name: "โรงพยาบาล",
      icon: "🏥",
      description: "โรงพยาบาลทั่วไป / โรงพยาบาลเฉพาะทาง / ศูนย์การแพทย์",
      subTypes: ["โรงพยาบาลทั่วไป", "โรงพยาบาลเฉพาะทาง", "ศูนย์การแพทย์"],
      requirements: ["มีใบอนุญาตประกอบการ", "มีแพทย์ผู้เชี่ยวชาญ", "ผ่านมาตรฐานความปลอดภัย"],
    },
    {
      code: "CLN",
      name: "คลินิกเฉพาะทาง",
      icon: "🏪",
      description: "คลินิกทันตกรรม / คลินิกความงาม / คลินิกจักษุ ฯลฯ",
      subTypes: ["ทันตกรรม", "ความงาม", "จักษุ", "กายภาพบำบัด"],
      requirements: ["มีแพทย์ประจำ", "อุปกรณ์มาตรฐาน", "ใบอนุญาตประกอบกิจการ"],
    },
    {
      code: "HTL",
      name: "โรงแรมและที่พัก",
      icon: "🏨",
      description: "โรงแรม 3-5 ดาว / เซอร์วิสอพาร์ตเมนต์",
      subTypes: ["โรงแรม 3 ดาว", "โรงแรม 4 ดาว", "โรงแรม 5 ดาว", "เซอร์วิสอพาร์ตเมนต์"],
      requirements: ["สิ่งอำนวยความสะดวกครบครัน", "รองรับผู้ป่วยและญาติ", "มีมาตรฐานความสะอาด"],
    },
    {
      code: "TRN",
      name: "บริการรับส่ง",
      icon: "🚗",
      description: "รถพยาบาล / รถรับส่งผู้ป่วย / รถตู้ VIP",
      subTypes: ["รถพยาบาล", "รถรับส่งผู้ป่วย", "รถตู้ VIP", "รถลีมูซีน"],
      requirements: ["มีประกันภัย", "พนักงานขับรถมืออาชีพ", "รถสภาพดีพร้อมใช้งาน"],
    },
    {
      code: "COR",
      name: "องค์กรและนักลงทุน",
      icon: "🏢",
      description: "บริษัทประกันภัย / DMC / ผู้พัฒนาโครงการ",
      subTypes: ["บริษัทประกันภัย", "DMC", "ผู้พัฒนาโครงการ", "ที่ปรึกษาทางการแพทย์"],
      requirements: ["มีประสบการณ์ในอุตสาหกรรม", "ฐานะการเงินมั่นคง", "พร้อมสนับสนุนการขยายเครือข่าย"],
    },
    {
      code: "WEL",
      name: "กลุ่มบริการ Wellness และ สปา",
      icon: "🌿",
      description: "สปา / นวดแผนไทย / ศูนย์สุขภาพองค์รวม / ดีท็อกซ์และฟื้นฟูร่างกาย",
      subTypes: ["สปา", "นวดแผนไทย", "ศูนย์เวลเนส", "ดีท็อกซ์/ฟื้นฟูร่างกาย"],
      requirements: ["มีใบอนุญาตประกอบกิจการสปา/นวด", "พนักงานผ่านการอบรมมาตรฐาน", "สถานที่สะอาดถูกสุขลักษณะ"],
    },
  ],
  phaseFocus: {
    label: "WOS Founding Partner Focus",
    headline: "Phase 1: Clinic & Wellness",
    description:
      "WOS กำลังให้ความสำคัญกับ Clinic, Wellness และ Healthcare Providers ที่มีศักยภาพในการให้บริการลูกค้าจากลาว",
  },
  howItWorks: [
    {
      stepNumber: 1,
      title: "Apply",
      description: "ส่งข้อมูลธุรกิจและบริการของท่านให้ทีม WOS",
      duration: "48 ชั่วโมง",
    },
    {
      stepNumber: 2,
      title: "Partner Review",
      description: "WOS ตรวจสอบคุณสมบัติและพูดคุยรูปแบบธุรกิจร่วมกัน",
      duration: "3-5 วัน",
    },
    {
      stepNumber: 3,
      title: "Package Setup",
      description: "ร่วมกันจัดทำ Service / Package สำหรับลูกค้าจากลาว",
      duration: "3-5 วัน",
    },
    {
      stepNumber: 4,
      title: "Pilot Agreement",
      description: "ตกลง Commercial Terms และ SLA ร่วมกัน",
      duration: "1-2 วัน",
    },
    {
      stepNumber: 5,
      title: "Go Live",
      description: "เปิดบริการบน WOS และเริ่มรับ Lead / Booking",
      duration: "ทันที",
    },
  ],
  operatingModel: {
    headline: "WOS ทำงานอย่างไร",
    flowSteps: [
      "นักท่องเที่ยว",
      "ค้นหาบริการ",
      "เปรียบเทียบพันธมิตร",
      "จองผ่าน WOS",
      "รับบริการจากพันธมิตร",
      "WOS ตรวจสอบคุณภาพ",
      "ชำระเงิน",
      "ติดตามผล",
    ],
    keyPoints: [
      "WOS ทำหน้าที่เป็นตัวกลางที่เชื่อถือได้ (Trusted Intermediary)",
      "WOS มีขั้นตอนตรวจสอบข้อมูลและคุณสมบัติของ Partner ก่อนเข้าร่วมเครือข่าย และติดตาม Feedback จากลูกค้า",
      "ประสานการชำระเงินตามรอบบิลที่ตกลงร่วมกัน",
      "เก็บข้อมูลและ Feedback เพื่อพัฒนาคุณภาพอย่างต่อเนื่อง",
    ],
  },
  benefits: [
    {
      title: "ระบบบริหารจัดการครบวงจร",
      description: "Partner Dashboard ใช้งานง่าย จัดการตารางเวลา ราคา และโปรโมชั่นได้เอง",
      icon: "✅",
      features: ["จัดการตารางเวลา", "ปรับราคาได้เอง", "สร้างโปรโมชั่น", "ดูประวัติการจอง"],
    },
    {
      title: "การตลาดและโปรโมท",
      description: "ปรากฏใน Partner Directory ได้รับการโปรโมทผ่านช่องทาง Social Media และ Newsletter",
      icon: "📢",
      features: ["Partner Directory", "โปรโมทผ่าน Social Media", "ขึ้น Newsletter", "ตรา WOS Trusted Partner"],
    },
    {
      title: "WOS Partner Support",
      description: "ทีม WOS ช่วยประสานงานด้านการจองและการให้บริการตามขอบเขตที่ตกลงกับ Partner",
      icon: "💬",
      features: ["ประสานงานการจอง", "ไทย/อังกฤษ", "ติดต่อผ่าน Line / WhatsApp"],
    },
    {
      title: "รายงานธุรกิจและข้อมูลการจอง",
      description: "ดูพฤติกรรมและความต้องการของลูกค้า พร้อมรายงานยอดขายและแนวโน้มการจอง",
      icon: "📊",
      features: ["ข้อมูลพฤติกรรมลูกค้า", "รายงานยอดขาย", "วิเคราะห์แนวโน้ม"],
    },
    {
      title: "การต่อยอดทางธุรกิจ",
      description: "โอกาสร่วมโครงการกับพันธมิตรรายอื่น เข้าร่วม Event และ Networking ระดับภูมิภาค",
      icon: "🤝",
      features: ["โครงการร่วมพันธมิตร", "อีเวนต์ระดับภูมิภาค", "Networking", "จับคู่ทางธุรกิจ"],
    },
  ],
  commercialTerms: {
    headline: "Commercial Model",
    intro:
      "Performance-based Partnership — WOS ไม่มีค่า Setup และไม่มี Monthly Platform Fee สำหรับ Founding Partner ในช่วง Pilot WOS จะได้รับค่าบริการ/Commission เมื่อเกิดธุรกรรมตามเงื่อนไขที่ตกลงร่วมกันใน Partner Agreement",
    docStamp: "Founding Partner Terms",
    terms: [
      { label: "ค่า Setup", value: "ไม่มี", note: "สำหรับ Founding Partner ในช่วง Pilot" },
      { label: "Monthly Platform Fee", value: "ไม่มี", note: "ในช่วง Pilot" },
      {
        label: "ค่าคอมมิชชั่น / ค่าบริการ",
        value: "คิดตามธุรกรรมจริง",
        note: "ตามเงื่อนไขที่ตกลงร่วมกันใน Partner Agreement",
      },
      { label: "รอบการชำระเงิน", value: "รายเดือน ภายใน 30 วันหลังปิดรอบบิล" },
      { label: "ระยะเวลาสัญญา", value: "1 ปี ต่ออายุอัตโนมัติ เว้นแต่แจ้งยกเลิกล่วงหน้า" },
      { label: "สกุลเงินการชำระเงิน", value: "THB / USD (ตามข้อตกลง)" },
    ],
    disclaimer:
      "รายละเอียดค่าคอมมิชชั่นและเงื่อนไขฉบับสมบูรณ์จะระบุใน Pilot Agreement / MOU ที่ลงนามร่วมกัน",
  },
  mou: {
    headline: "MOU และข้อตกลงความร่วมมือ",
    intro:
      "ทุกพันธมิตรของ WOS ลงนามในบันทึกข้อตกลงความร่วมมือ (MOU) ก่อนเริ่มให้บริการ เพื่อกำหนดสิทธิ หน้าที่ และมาตรฐานการทำงานร่วมกันอย่างชัดเจน",
    documentIncludes: [
      "ขอบเขตความร่วมมือและประเภทบริการ",
      "เงื่อนไขทางการค้าและรอบการชำระเงิน",
      "มาตรฐานคุณภาพและ SLA",
      "นโยบายความเป็นส่วนตัวและการคุ้มครองข้อมูลลูกค้า",
      "เงื่อนไขการต่ออายุและการยกเลิกสัญญา",
    ],
    signingSteps: [
      "ทีม WOS จัดส่งร่าง MOU หลังผ่านการตรวจสอบคุณสมบัติ",
      "ทั้งสองฝ่ายทบทวนและเจรจาเงื่อนไข (ถ้ามี)",
      "ลงนามผ่านระบบลงนามอิเล็กทรอนิกส์หรือเอกสารต้นฉบับ",
      "จัดเก็บสำเนา MOU ในระบบ Partner Dashboard ของท่าน",
    ],
    downloadLabel: "ขอตัวอย่างร่าง MOU",
    downloadNote: "ทีมงานจะจัดส่งตัวอย่างเอกสารให้ทางอีเมลหลังจากยืนยันคุณสมบัติเบื้องต้น",
  },
  responsibilitiesSla: {
    headline: "ความรับผิดชอบ และ SLA",
    intro: "แบ่งบทบาทหน้าที่ระหว่าง WOS และพันธมิตรให้ชัดเจน พร้อมมาตรฐานเวลาตอบสนองที่ตกลงร่วมกัน",
    responsibilities: [
      { area: "การตลาดและการหาลูกค้า", wos: "จัดหาและคัดกรองนักท่องเที่ยวเชิงการแพทย์", partner: "ให้ข้อมูลบริการที่ถูกต้องและเป็นปัจจุบัน" },
      { area: "การจองและยืนยัน", wos: "จัดการระบบจองผ่านแพลตฟอร์ม", partner: "ยืนยันหรือปฏิเสธคำขอจองภายในเวลาที่กำหนด" },
      { area: "คุณภาพบริการ", wos: "ตรวจสอบคุณภาพและรับ Feedback จากผู้ใช้", partner: "ให้บริการตามมาตรฐานที่ตกลงใน MOU" },
      { area: "การชำระเงิน", wos: "โอนเงินตามรอบบิลที่กำหนด", partner: "ออกใบเสร็จ/เอกสารทางบัญชีที่ถูกต้อง" },
      { area: "ข้อมูลลูกค้า", wos: "คุ้มครองข้อมูลตามนโยบายความเป็นส่วนตัว", partner: "ใช้ข้อมูลลูกค้าเฉพาะเพื่อการให้บริการที่จองผ่าน WOS" },
    ],
    slaHeadline: "มาตรฐานเวลาตอบสนอง (SLA)",
    slaItems: [
      { label: "ยืนยันการจอง", target: "ภายใน 4 ชั่วโมงทำการ" },
      { label: "ตอบกลับข้อซักถามลูกค้า", target: "ภายใน 24 ชั่วโมง" },
      { label: "แจ้งปัญหาเร่งด่วน (Urgent Case)", target: "ภายใน 1 ชั่วโมง" },
      { label: "รอบการชำระเงินพันธมิตร", target: "ภายใน 30 วันหลังปิดรอบบิล" },
    ],
  },
  prepare: {
    eyebrow: "PARTNER CHECKLIST",
    headline: "Partner ต้องเตรียมอะไร",
    items: [
      "ข้อมูลบริษัท / ธุรกิจ",
      "ใบอนุญาตที่เกี่ยวข้อง",
      "รายการบริการ",
      "ราคา",
      "รูปภาพบริการ / สถานที่",
      "ตารางเวลาที่ให้บริการได้",
      "นโยบายการยกเลิก",
      "ผู้ติดต่อหลัก",
      "ข้อมูลการรับชำระเงิน",
      "Service Package สำหรับลูกค้าต่างชาติ",
    ],
    ctaText: "เริ่มสมัครเป็น WOS Founding Partner",
    ctaLink: "/partner/apply",
  },
  cta: {
    headline: "พร้อมที่จะเติบโตไปด้วยกันหรือยัง?",
    subtext: "เริ่มต้นความร่วมมือกับ WOS วันนี้ เพียงคลิกปุ่มด้านล่าง ทีมงานของเราจะติดต่อคุณภายใน 48 ชั่วโมง",
    buttonText: "เริ่มต้นเป็นพันธมิตร →",
    buttonLink: "/partner/apply",
    gateLabel: "BOARDING NOW",
  },
  seo: {
    title: "เป็นพันธมิตรกับ WOS | Medical Tourism Partner Network",
    description: "ร่วมเป็นพันธมิตรกับ WOS ระบบนิเวศการท่องเที่ยวเชิงการแพทย์ที่โปร่งใส ปลอดภัย และเติบโตอย่างยั่งยืน",
    keywords: ["พันธมิตร", "การท่องเที่ยวเชิงการแพทย์", "WOS", "โรงพยาบาล", "คลินิก", "โรงแรม", "บริการรับส่ง"],
  },
  applyForm: {
    eyebrow: "PARTNER APPLICATION",
    headline: "สมัครเป็นพันธมิตรกับ WOS",
    subheadline: "กรอกข้อมูลด้านล่าง ทีมงานจะตรวจสอบและติดต่อกลับภายใน 48 ชั่วโมง",
    sections: {
      company: "ข้อมูลองค์กร",
      contact: "ข้อมูลผู้ติดต่อ",
      services: "ประเภทและบริการ",
      consent: "ยืนยันการสมัคร",
    },
    fields: {
      companyName: "ชื่อองค์กร / สถานประกอบการ",
      registrationNumber: "เลขทะเบียนนิติบุคคล",
      taxId: "เลขประจำตัวผู้เสียภาษี",
      businessType: "ประเภทธุรกิจ",
      businessTypeOptions: [
        { value: "HOSPITAL", label: "โรงพยาบาล" },
        { value: "CLINIC", label: "คลินิกเฉพาะทาง" },
        { value: "HOTEL", label: "โรงแรมและที่พัก" },
        { value: "TRANSPORT", label: "บริการรับส่ง" },
        { value: "CORPORATE", label: "องค์กรและนักลงทุน" },
        { value: "WELLNESS_SPA", label: "กลุ่มบริการ Wellness และ สปา" },
      ],
      yearEstablished: "ปีที่ก่อตั้ง",
      employeeCount: "จำนวนพนักงาน",
      primaryName: "ชื่อผู้ติดต่อหลัก",
      primaryTitle: "ตำแหน่ง",
      primaryEmail: "อีเมล",
      primaryPhone: "เบอร์โทรศัพท์",
      primaryLineId: "Line ID",
      address: "ที่อยู่",
      district: "เขต/อำเภอ",
      province: "จังหวัด",
      postalCode: "รหัสไปรษณีย์",
      serviceTypes: "บริการที่ให้ (เลือกได้มากกว่า 1)",
      languages: "ภาษาที่ให้บริการ",
      operatingHours: "เวลาทำการ",
      capacity: "ความสามารถในการรองรับ (เช่น จำนวนเตียง/ห้อง/คัน)",
    },
    consent: {
      acceptTerms: "ข้าพเจ้ายอมรับข้อกำหนดและเงื่อนไขการเป็นพันธมิตรของ WOS",
      acceptPrivacy: "ข้าพเจ้ายอมรับนโยบายความเป็นส่วนตัวของ WOS",
      acceptSLA: "ข้าพเจ้ารับทราบและยินยอมปฏิบัติตามมาตรฐาน SLA ที่กำหนด",
    },
    submitLabel: "ส่งใบสมัคร",
    submittingLabel: "กำลังส่งข้อมูล...",
    successTitle: "ส่งใบสมัครสำเร็จ",
    successBody: "ขอบคุณสำหรับความสนใจ ทีมงาน WOS จะติดต่อกลับภายใน 48 ชั่วโมง",
    errorTitle: "ส่งใบสมัครไม่สำเร็จ",
    errorBody: "กรุณาลองใหม่อีกครั้ง หรือติดต่อทีมงานโดยตรงหากปัญหายังคงอยู่",
  },
};
