// content/partner/th.ts
import type { PartnerPageContent } from "./types";

export const th: PartnerPageContent = {
  locale: "th",
  nav: {
    brand: "WOS Partner",
    mobileBrand: "WOS Partner",
    links: [
      { label: "Partner Benefits", href: "#why-partner" },
      { label: "How It Works", href: "#how-it-works" },
      { label: "Founding Partner", href: "#founding-partner" },
    ],
    cta: { label: "Apply Now", href: "/partner/apply" },
    mobileCtaLabel: "Apply",
  },
  hero: {
    eyebrow: "WOS PARTNER NETWORK",
    headlineLines: ["เชื่อมธุรกิจของคุณ", "กับลูกค้าจากลาว"],
    description:
      "WOS เชื่อมลูกค้าจากลาวกับ Healthcare & Wellness ในประเทศไทย พร้อมดูแลตั้งแต่การวางแผน การจอง การเดินทาง จนถึงหลังรับบริการ",
    highlight: "Thailand × Laos",
    primaryCta: { label: "Become a Founding Partner", href: "/partner/apply" },
    secondaryCta: { label: "ดูรายละเอียด Partnership", href: "#why-partner" },
    visual: { from: "Laos Customer", via: "WOS", to: "Thai Partner" },
  },
  whyPartner: {
    eyebrow: "WHY PARTNER WITH WOS",
    headline: "เข้าถึงลูกค้าใหม่",
    subheadline: "พร้อมบริการที่มากกว่าการจอง",
    cards: [
      {
        index: "01",
        title: "Reach New Customers",
        description: "เข้าถึงลูกค้าจากลาวที่มองหา Healthcare & Wellness ในประเทศไทย",
      },
      {
        index: "02",
        title: "One Complete Journey",
        description: "WOS ช่วยประสานตั้งแต่ Booking, Transport, Hotel จนถึงการเข้ารับบริการ",
      },
      {
        index: "03",
        title: "Performance-Based",
        description: "ไม่มี Setup Fee และ Monthly Platform Fee ในช่วง Founding Pilot",
      },
    ],
  },
  journey: {
    eyebrow: "ONE COMPLETE JOURNEY",
    headline: "จากลาวสู่ไทย",
    subheadline: "WOS ดูแลตลอด Journey",
    steps: [
      { index: "01", title: "Discover", description: "ลูกค้าจากลาวค้นพบบริการที่เหมาะกับความต้องการ" },
      { index: "02", title: "Plan", description: "WOS ช่วยเลือกโปรแกรมและวางแผนการเดินทาง" },
      { index: "03", title: "Travel", description: "ประสาน Transport / Hotel / Appointment" },
      { index: "04", title: "Care", description: "ลูกค้าเข้ารับบริการกับ WOS Partner" },
      { index: "05", title: "Return", description: "WOS ช่วยดูแลและประสานงานจนลูกค้ากลับประเทศ" },
    ],
    highlightTitle: "One Complete Journey",
    highlightText: "ไม่ใช่แค่ Booking แต่คือการดูแล Customer Journey ตั้งแต่ต้นจนจบ",
  },
  whoCanJoin: {
    eyebrow: "WHO CAN JOIN",
    headline: "WOS Partner Network",
    intro: "เรากำลังสร้างเครือข่าย Healthcare, Wellness และ Hospitality สำหรับลูกค้าจากลาว",
    groups: [
      { name: "Healthcare", items: ["โรงพยาบาล", "คลินิก", "ทันตกรรม", "ศูนย์เฉพาะทาง"] },
      { name: "Wellness", items: ["Wellness Center", "Longevity", "Spa", "Recovery"] },
      { name: "Hospitality & Travel", items: ["Hotel", "Transport", "Travel Support"] },
    ],
    note: "Additional partner categories will be added as the network expands.",
  },
  foundingPartner: {
    eyebrow: "WOS FOUNDING PARTNER",
    headline: "Join the First Partner Network",
    intro:
      "ร่วมเป็นหนึ่งใน Partner รุ่นแรกของ WOS และร่วมออกแบบบริการสำหรับตลาดลาวไปกับทีม WOS",
    privilegesHeadline: "Founding Partner Privileges",
    privileges: [
      { title: "No Setup Fee", description: "ไม่มีค่า Setup" },
      { title: "No Monthly Platform Fee", description: "ไม่มีค่ารายเดือนในช่วง Pilot" },
      { title: "Priority Onboarding", description: "ได้รับสิทธิ์ในการ Onboarding ก่อน" },
      { title: "Package Co-Design", description: "ร่วมออกแบบ Package สำหรับตลาดลาว" },
      { title: "Partner Profile on WOS", description: "นำเสนอธุรกิจผ่าน WOS" },
      { title: "Cross-border Customer Opportunities", description: "โอกาสรับลูกค้าจากตลาดลาว" },
    ],
    badge: "LIMITED FIRST COHORT",
    cta: { label: "Become a Founding Partner", href: "/partner/apply" },
  },
  howItWorks: {
    eyebrow: "HOW IT WORKS",
    headline: "เริ่มต้นกับ WOS ง่าย ๆ",
    steps: [
      { index: "01", title: "Apply", description: "ส่งข้อมูล Partner" },
      { index: "02", title: "Review", description: "ทีม WOS พูดคุยและตรวจสอบข้อมูล" },
      { index: "03", title: "Build", description: "ร่วมออกแบบ Package / Service สำหรับตลาดลาว" },
      { index: "04", title: "Launch", description: "เริ่มรับ Customer Journey ผ่าน WOS" },
    ],
    ctaHeadline: "Ready to grow with WOS?",
    cta: { label: "Become a Founding Partner", href: "/partner/apply" },
  },
  commercialModel: {
    eyebrow: "COMMERCIAL MODEL",
    headline: "Simple & Performance-Based",
    subheadline: "โครงสร้างค่าใช้จ่ายที่เข้าใจง่าย และเกิดขึ้นเมื่อมีธุรกรรมจริง",
    cards: [
      { lead: "NO", term: "SETUP FEE", note: "ไม่มีค่า Setup ในช่วง Founding Pilot" },
      { lead: "NO", term: "MONTHLY FEE", note: "ไม่มีค่ารายเดือนในช่วง Pilot" },
      {
        lead: "PAY",
        term: "WHEN BUSINESS HAPPENS",
        note: "เกิดค่าใช้บริการเมื่อเกิดธุรกรรม — รูปแบบ Commercial และ Commission ตกลงตามประเภท Partner และรูปแบบบริการ",
      },
    ],
    termsLink: { label: "View Partnership Terms", href: "/partner/terms" },
  },
  requirements: {
    eyebrow: "PARTNER REQUIREMENTS",
    headline: "สิ่งที่ Partner ต้องเตรียม",
    items: [
      "Business / Service Information",
      "Price & Package",
      "Availability / Booking Conditions",
      "Contact Person",
      "Supporting Documents",
    ],
    note: "ทีม WOS จะช่วยแนะนำและประสานขั้นตอนการ Onboarding",
  },
  cta: {
    eyebrow: "JOIN THE NETWORK",
    headline: "พร้อมเติบโตไปกับตลาดลาว?",
    subheadline: "ร่วมเป็น WOS Founding Partner",
    description:
      "WOS กำลังเปิดรับ Partner รุ่นแรกสำหรับการขยายตลาด Healthcare & Wellness ระหว่างลาวและประเทศไทย",
    primaryCta: { label: "Become a Founding Partner", href: "/partner/apply" },
    secondaryCta: { label: "Talk to WOS Team", href: "/consultation" },
  },
  termsPage: {
    eyebrow: "PARTNERSHIP TERMS",
    headline: "รายละเอียดความร่วมมือ",
    intro:
      "รายละเอียดเชิงพาณิชย์ ข้อตกลง MOU ความรับผิดชอบ และมาตรฐานการให้บริการ สำหรับ Partner ที่ต้องการศึกษาเงื่อนไขก่อนตัดสินใจ",
    backLabel: "กลับไปหน้า Partner",
    ctaHeadline: "พร้อมเริ่มต้นกับ WOS แล้วใช่ไหม?",
    cta: { label: "Become a Founding Partner", href: "/partner/apply" },
  },
  commercialTerms: {
    headline: "Commercial Model",
    intro:
      "Performance-based Partnership — WOS ไม่มีค่า Setup และไม่มี Monthly Platform Fee สำหรับ Founding Partner ในช่วง Pilot WOS จะได้รับค่าบริการ/Commission เมื่อเกิดธุรกรรมตามเงื่อนไขที่ตกลงร่วมกันใน Partner Agreement",
    docStamp: "Founding Partner Terms",
    terms: [
      { label: "ค่า Setup", value: "ไม่มี", note: "สำหรับ Founding Partner ในช่วง Pilot" },
      { label: "Monthly Platform Fee", value: "ไม่มี", note: "ในช่วง Pilot" },
      {
        label: "ค่าคอมมิชชั่น / ค่าบริการ",
        value: "คิดตามธุรกรรมจริง",
        note: "ตามเงื่อนไขที่ตกลงร่วมกันใน Partner Agreement",
      },
      { label: "รอบการชำระเงิน", value: "รายเดือน ภายใน 30 วันหลังปิดรอบบิล" },
      { label: "ระยะเวลาสัญญา", value: "1 ปี ต่ออายุอัตโนมัติ เว้นแต่แจ้งยกเลิกล่วงหน้า" },
      { label: "สกุลเงินการชำระเงิน", value: "THB / USD (ตามข้อตกลง)" },
    ],
    feeScheduleHeadline: "อัตราค่าธรรมเนียมตามประเภทพันธมิตร",
    feeSchedule: [
      { icon: "🏥", category: "Clinic / Medical Provider", fee: "15%", principle: "คิดจากบริการที่เกิดจาก WOS" },
      { icon: "🌿", category: "Wellness / Spa", fee: "15%", principle: "ขึ้นกับบริการและ margin" },
      { icon: "🏨", category: "Hotel / Resort", fee: "12%", principle: "เหมาะกับโรงแรมที่มี volume" },
      { icon: "🚐", category: "Transport", fee: "15%", principle: "Sedan/SUV/Van/รถ VIP" },
      { icon: "🧘", category: "Fitness / Yoga / Activity", fee: "15%", principle: "Package / Activity" },
      { icon: "🥗", category: "Healthy Food", fee: "10%", principle: "margin ค่อนข้างต่ำ" },
      { icon: "🥊", category: "Muay Thai / Training", fee: "15%", principle: "Package ระยะสั้น/ยาว" },
      { icon: "👨‍⚕️", category: "Specialist / Consultant", fee: "10%", principle: "ค่าบริการวิชาชีพ" },
      { icon: "📦", category: "WOS Bundled Journey", fee: "20%+", principle: "WOS รวมหลายบริการและบริหาร Journey" },
    ],
    feeScheduleNote:
      "อัตราค่าธรรมเนียมอาจปรับตามปริมาณการจอง ระยะเวลาสัญญา และรูปแบบความร่วมมือ — ติดต่อทีม WOS เพื่อรับข้อเสนอที่เหมาะกับธุรกิจของคุณ",
    disclaimer:
      "รายละเอียดค่าคอมมิชชั่นและเงื่อนไขฉบับสมบูรณ์จะระบุใน Pilot Agreement / MOU ที่ลงนามร่วมกัน",
  },
  mou: {
    headline: "MOU และข้อตกลงความร่วมมือ",
    intro:
      "ทุกพันธมิตรของ WOS ลงนามในบันทึกข้อตกลงความร่วมมือ (MOU) ก่อนเริ่มให้บริการ เพื่อกำหนดสิทธิ หน้าที่ และมาตรฐานการทำงานร่วมกันอย่างชัดเจน",
    documentIncludes: [
      "ขอบเขตความร่วมมือและประเภทบริการ",
      "เงื่อนไขทางการค้าและรอบการชำระเงิน",
      "มาตรฐานคุณภาพและ SLA",
      "นโยบายความเป็นส่วนตัวและการคุ้มครองข้อมูลลูกค้า",
      "เงื่อนไขการต่ออายุและการยกเลิกสัญญา",
    ],
    signingSteps: [
      "ทีม WOS จัดส่งร่าง MOU หลังผ่านการตรวจสอบคุณสมบัติ",
      "ทั้งสองฝ่ายทบทวนและเจรจาเงื่อนไข (ถ้ามี)",
      "ลงนามผ่านระบบลงนามอิเล็กทรอนิกส์หรือเอกสารต้นฉบับ",
      "จัดเก็บสำเนา MOU ในระบบ Partner Dashboard ของท่าน",
    ],
    downloadLabel: "ขอตัวอย่างร่าง MOU",
    downloadNote: "ทีมงานจะจัดส่งตัวอย่างเอกสารให้ทางอีเมลหลังจากยืนยันคุณสมบัติเบื้องต้น",
  },
  responsibilitiesSla: {
    headline: "ความรับผิดชอบ และ SLA",
    intro: "แบ่งบทบาทหน้าที่ระหว่าง WOS และพันธมิตรให้ชัดเจน พร้อมมาตรฐานเวลาตอบสนองที่ตกลงร่วมกัน",
    responsibilities: [
      { area: "การตลาดและการหาลูกค้า", wos: "จัดหาและคัดกรองนักท่องเที่ยวเชิงการแพทย์", partner: "ให้ข้อมูลบริการที่ถูกต้องและเป็นปัจจุบัน" },
      { area: "การจองและยืนยัน", wos: "จัดการระบบจองผ่านแพลตฟอร์ม", partner: "ยืนยันหรือปฏิเสธคำขอจองภายในเวลาที่กำหนด" },
      { area: "คุณภาพบริการ", wos: "ตรวจสอบคุณภาพและรับ Feedback จากผู้ใช้", partner: "ให้บริการตามมาตรฐานที่ตกลงใน MOU" },
      { area: "การชำระเงิน", wos: "โอนเงินตามรอบบิลที่กำหนด", partner: "ออกใบเสร็จ/เอกสารทางบัญชีที่ถูกต้อง" },
      { area: "ข้อมูลลูกค้า", wos: "คุ้มครองข้อมูลตามนโยบายความเป็นส่วนตัว", partner: "ใช้ข้อมูลลูกค้าเฉพาะเพื่อการให้บริการที่จองผ่าน WOS" },
    ],
    slaHeadline: "มาตรฐานเวลาตอบสนอง (SLA)",
    slaItems: [
      { label: "ยืนยันการจอง", target: "ภายใน 4 ชั่วโมงทำการ" },
      { label: "ตอบกลับข้อซักถามลูกค้า", target: "ภายใน 24 ชั่วโมง" },
      { label: "แจ้งปัญหาเร่งด่วน (Urgent Case)", target: "ภายใน 1 ชั่วโมง" },
      { label: "รอบการชำระเงินพันธมิตร", target: "ภายใน 30 วันหลังปิดรอบบิล" },
    ],
  },
  seo: {
    title: "เป็นพันธมิตรกับ WOS | Medical Tourism Partner Network",
    description: "ร่วมเป็นพันธมิตรกับ WOS ระบบนิเวศการท่องเที่ยวเชิงการแพทย์ที่โปร่งใส ปลอดภัย และเติบโตอย่างยั่งยืน",
    keywords: ["พันธมิตร", "การท่องเที่ยวเชิงการแพทย์", "WOS", "โรงพยาบาล", "คลินิก", "โรงแรม", "บริการรับส่ง"],
  },
  applyForm: {
    eyebrow: "PARTNER APPLICATION",
    headline: "Apply to Become a Founding Partner",
    subheadline: "กรอกข้อมูลด้านล่าง ทีมงานจะตรวจสอบและติดต่อกลับภายใน 48 ชั่วโมง",
    sections: {
      company: "ข้อมูลองค์กร",
      contact: "ข้อมูลผู้ติดต่อ",
      services: "ประเภทและบริการ",
      consent: "ยืนยันการสมัคร",
    },
    fields: {
      companyName: "ชื่อองค์กร / สถานประกอบการ",
      registrationNumber: "เลขทะเบียนนิติบุคคล",
      taxId: "เลขประจำตัวผู้เสียภาษี",
      businessType: "ประเภทธุรกิจ",
      businessTypeOptions: [
        { value: "HOSPITAL", label: "โรงพยาบาล" },
        { value: "CLINIC", label: "คลินิกเฉพาะทาง" },
        { value: "HOTEL", label: "โรงแรมและที่พัก" },
        { value: "TRANSPORT", label: "บริการรับส่ง" },
        { value: "CORPORATE", label: "องค์กรและนักลงทุน" },
        { value: "WELLNESS_SPA", label: "กลุ่มบริการ Wellness และ สปา" },
      ],
      yearEstablished: "ปีที่ก่อตั้ง",
      employeeCount: "จำนวนพนักงาน",
      primaryName: "ชื่อผู้ติดต่อหลัก",
      primaryTitle: "ตำแหน่ง",
      primaryEmail: "อีเมล",
      primaryPhone: "เบอร์โทรศัพท์",
      primaryLineId: "Line ID",
      address: "ที่อยู่",
      district: "เขต/อำเภอ",
      province: "จังหวัด",
      postalCode: "รหัสไปรษณีย์",
      serviceTypes: "บริการที่ให้ (เลือกได้มากกว่า 1)",
      languages: "ภาษาที่ให้บริการ",
      operatingHours: "เวลาทำการ",
      capacity: "ความสามารถในการรองรับ (เช่น จำนวนเตียง/ห้อง/คัน)",
    },
    consent: {
      acceptTerms: "ข้าพเจ้ายอมรับข้อกำหนดและเงื่อนไขการเป็นพันธมิตรของ WOS",
      acceptPrivacy: "ข้าพเจ้ายอมรับนโยบายความเป็นส่วนตัวของ WOS",
      acceptSLA: "ข้าพเจ้ารับทราบและยินยอมปฏิบัติตามมาตรฐาน SLA ที่กำหนด",
    },
    submitLabel: "ส่งใบสมัคร",
    submittingLabel: "กำลังส่งข้อมูล...",
    successTitle: "ส่งใบสมัครสำเร็จ",
    successBody: "ขอบคุณสำหรับความสนใจ ทีมงาน WOS จะติดต่อกลับภายใน 48 ชั่วโมง",
    errorTitle: "ส่งใบสมัครไม่สำเร็จ",
    errorBody: "กรุณาลองใหม่อีกครั้ง หรือติดต่อทีมงานโดยตรงหากปัญหายังคงอยู่",
    validationError: "กรุณากรอกข้อมูลในช่องที่มีเครื่องหมาย * ให้ครบถ้วน",
  },
};
